list: $/renatio/dynamicpdf/models/template/columns.yaml

modelClass: Renatio\DynamicPDF\Models\Template

title: renatio.dynamicpdf::lang.templates.label

recordUrl: renatio/dynamicpdf/templates/update/:id

noRecordsMessage: backend::lang.list.no_records

recordsPerPage: 20

showSetup: true

showSorting: true

defaultSort:
     column: created_at
     direction: desc

showCheckboxes: false

toolbar:
    buttons: list_templates_toolbar

    search:
        prompt: backend::lang.list.search_prompt