list: $/renatio/dynamicpdf/models/layout/columns.yaml

modelClass: Renatio\DynamicPDF\Models\Layout

title: renatio.dynamicpdf::lang.layouts.label

recordUrl: renatio/dynamicpdf/layouts/update/:id

noRecordsMessage: backend::lang.list.no_records

recordsPerPage: 20

showSetup: true

showSorting: true

defaultSort:
     column: created_at
     direction: desc

showCheckboxes: false

toolbar:
    buttons: list_layouts_toolbar

    search:
        prompt: backend::lang.list.search_prompt