name: renatio.dynamicpdf::lang.template.menu_label

form: $/renatio/dynamicpdf/models/template/fields.yaml

modelClass: Renatio\DynamicPDF\Models\Template

defaultRedirect: renatio/dynamicpdf/templates

create:
    title: renatio.dynamicpdf::lang.template.create_template
    redirect: renatio/dynamicpdf/templates/update/:id
    redirectClose: renatio/dynamicpdf/templates

update:
    title: renatio.dynamicpdf::lang.template.edit_template
    redirect: renatio/dynamicpdf/templates
    redirectClose: renatio/dynamicpdf/templates

preview:
    title: renatio.dynamicpdf::lang.templates.preview_html

permissions:
    modelCreate: renatio.dynamicpdf.manage_templates.create
    modelUpdate: renatio.dynamicpdf.manage_templates.update
    modelDelete: renatio.dynamicpdf.manage_templates.delete
    modelPreview: renatio.dynamicpdf.manage_templates.preview